// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbJ6NmJ_Ai4_Sj2CoUsxFnmBKF3472dj0',
    appId: '1:94620745762:web:de360b0c9576fc4a038a7b',
    messagingSenderId: '94620745762',
    projectId: 'auth-13863',
    authDomain: 'auth-13863.firebaseapp.com',
    storageBucket: 'auth-13863.firebasestorage.app',
    measurementId: 'G-9NRJW66G3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwM8Uw4AJUYsLZf19wbUXaroTxSdodJcE',
    appId: '1:94620745762:android:c19006ad1aa53d03038a7b',
    messagingSenderId: '94620745762',
    projectId: 'auth-13863',
    storageBucket: 'auth-13863.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXdI2qa_-ktvmgeoqKPvHPB_Z4n9fFW8E',
    appId: '1:94620745762:ios:41613c3f2bafd97a038a7b',
    messagingSenderId: '94620745762',
    projectId: 'auth-13863',
    storageBucket: 'auth-13863.firebasestorage.app',
    iosBundleId: 'com.example.fb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXdI2qa_-ktvmgeoqKPvHPB_Z4n9fFW8E',
    appId: '1:94620745762:ios:41613c3f2bafd97a038a7b',
    messagingSenderId: '94620745762',
    projectId: 'auth-13863',
    storageBucket: 'auth-13863.firebasestorage.app',
    iosBundleId: 'com.example.fb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbJ6NmJ_Ai4_Sj2CoUsxFnmBKF3472dj0',
    appId: '1:94620745762:web:0521e01ff112ccac038a7b',
    messagingSenderId: '94620745762',
    projectId: 'auth-13863',
    authDomain: 'auth-13863.firebaseapp.com',
    storageBucket: 'auth-13863.firebasestorage.app',
    measurementId: 'G-S5V2NZXLZB',
  );
}
